Epicure-master/epicures/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('rating/', include('rating.urls')),
    path('admin/', admin.site.urls),
]

Epicure-master/rating/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),

    path('detail/<int:res_ID>/', views.detail, name='detail'), 
    path('delete/<int:res_ID>', views.destroy, name='delete'),
    path('edit/<int:res_ID>', views.edit, name='edit'),
    path('update/<int:res_ID>', views.update, name='update'), 
    path('insert', views.insert, name='insert'),
    path('res', views.res, name='res'), 
    path('search', views.search, name='search'), 
    path('result', views.searchResult, name='result'), 
    path('recommend', views.recommend, name='recommend'),
    path('price_re', views.price_re, name='price_re'), 

]

Epicure-master/rating/models.py
from django.db import models

# Create your models here.
class Restaurant(models.Model):
    res_ID = models.CharField(max_length=200,primary_key=True)
    name = models.CharField(max_length=200,null=True)
    averageRating=models.FloatField(null=True)
    Cuisine_Type = models.CharField(max_length=255,null=True)
    Price_Range = models.CharField(max_length = 200,null=True)
    Phone = models.CharField(max_length = 200,null=True)
    Address = models.CharField(max_length=255,null=True)
    Hours_Start = models.CharField(max_length = 200,null=True)
    Hours_End = models.CharField(max_length = 200,null=True)

    def __str__(self):
        return self.name


class Dish(models.Model):
    name = models.CharField(max_length=200)
    price = models.FloatField(default=0,null=True)
    dish_type = models.CharField(max_length=200,null=True)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    class Meta:
        unique_together = (('restaurant', 'name'),)

    def __str__(self):
        return self.name

# class User(models.Model):
#     ID = models.IntegerField(max_length=200,primary_key=True)
#     name = models.CharField(max_length=200,null=True)
#     Password = models.CharField(max_length=255,null=True)
#     Major = models.CharField(max_length = 200,null=True)
#     Gender = models.CharField(max_length = 10,null=True)
#     Favorite_Cuisine_Type = models.CharField(max_length=255,null=True)
#     Favorite_Restaurant_Type = models.CharField(max_length = 200,null=True)

#     def __str__(self):
#         return self.name

Epicure-master/rating/forms.py
from django import forms  
from .models import Restaurant  
class RestaurantForm(forms.ModelForm):  
    class Meta:  
        model = Restaurant  
        fields = ('name', 'Address','Phone')

class CompleteForm(forms.ModelForm):  
    class Meta:  
        model = Restaurant  
        fields = ('name', 'Address','Phone','res_ID')

Epicure-master/rating/views.py
from django.shortcuts import render,get_object_or_404,redirect  
from .models import Restaurant,Dish
from django.http import HttpResponse
from .forms import RestaurantForm,CompleteForm
from django.db import connection
from django.template import loader

def index(request):
    res_list = Restaurant.objects.order_by('res_ID')[:]
    context = {'res_list': res_list}
    return render(request, 'rating/index.html', context)


def detail(request, res_ID):
    res_list = Restaurant.objects.get(pk=res_ID)
    menu = Dish.objects.filter(restaurant_id=res_ID)
    context = {'res_list': res_list, 'menu':menu}
    return render(request, 'rating/detail.html', context)


def destroy(request, res_ID):  
    restaurant = Restaurant.objects.get(res_ID=res_ID)  
    restaurant.delete()  
    return redirect("/rating") 

def edit(request, res_ID):  
    restaurant = Restaurant.objects.get(res_ID=res_ID)  
    return render(request,'rating/edit.html', {'restaurant':restaurant})  

def update(request, res_ID):  
    restaurant = Restaurant.objects.get(pk=res_ID)
    form = RestaurantForm(request.POST, instance = restaurant)  
    if form.is_valid():  
        form.save()  
        return redirect("/rating")   
    return redirect("/rating") 

def insert(request):  
    return render(request,'rating/insert.html') 

def res(request):   

    if request.method == "POST":  
        form = CompleteForm(request.POST)  
       
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/rating')  
            except:  
                pass  
    else:  
        form = CompleteForm()  
    return render(request,'/rating/insert.html',{'form':form})  

def convert(stri):
    if not stri: stri = None
    return stri


def price_re(request):
    price = convert(request.POST.get('price'))
    print(dish_type)
    with connection.cursor() as cursor:
        cursor.execute('''SELECT DISTINCT R1.Name, M1.Name, M1.price
            FROM rating_Restaurant R1, rating_Dish M1
            WHERE M1.price< %s AND R1.res_ID=M1.restaurant_id AND M1.restaurant_id IN
            (SELECT R.res_ID
            FROM rating_Dish M JOIN rating_Restaurant R
            ON R.res_ID=M.restaurant_id AND M.price< %s
            GROUP BY R.res_ID)
            ORDER BY M1.price
            LIMIT 10
            ''',[price])
        dish_list = cursor.fetchall()
    print("recommend: ", dish_list[0][0])
    # dish = [i[0] for i in dish]
    # dish_list = Dish.objects.filter(pk__in=restaurant)
    template = loader.get_template('rating/result.html')
    context = {'dish_list': dish_list}
    return HttpResponse(template.render(context, request))

def recommend(request):
    dish_type = convert(request.POST.get('dish_type'))
    print(dish_type)
    with connection.cursor() as cursor:
        cursor.execute('''SELECT DISTINCT R1.Name, M1.Name, M1.price
            FROM rating_Restaurant R1, rating_Dish M1
            WHERE M1.dish_type like "sal%" AND R1.res_ID=M1.restaurant_id AND M1.restaurant_id IN
            (SELECT R.res_ID
            FROM rating_Dish M JOIN rating_Restaurant R
            ON R.res_ID=M.restaurant_id AND M.dish_type like "sal%"
            GROUP BY R.res_ID)
            ORDER BY M1.price
            LIMIT 10''') #,
            # [dish_type])
        dish_list = cursor.fetchall()
    print("recommend: ", dish_list[0][0])
    # dish = [i[0] for i in dish]
    # dish_list = Dish.objects.filter(pk__in=restaurant)
    template = loader.get_template('rating/result.html')
    context = {'dish_list': dish_list}
    return HttpResponse(template.render(context, request))

def search(request):
    r_name = convert(request.POST.get('name'))
    cuision_type = convert(request.POST.get('cuision_type'))
    address = convert(request.POST.get('address'))

    with connection.cursor() as cursor:
        cursor.execute('''SELECT r.res_ID FROM rating_Restaurant r
                          WHERE r.name = IFNULL(%s,r.name) AND r.Cuisine_Type = IFNULL(%s,r.Cuisine_Type) AND r.address = IFNULL(%s, r.address)''',
                       [r_name,cuision_type,address])
        restaurant = cursor.fetchall()

    res_list = restaurant
    template = loader.get_template('rating/result.html')
    context = {'res_list': res_list}
    return HttpResponse(template.render(context, request))


def searchResult(request, res_list):
    context = {'res_list': res_list}
    return render(request, 'rating/result.html', context)

Epicure-master/rating/templates/rating/detail.html
<!DOCTYPE html>
<html lang="en" >
    <body>  

	<div class="content-section">
	  <div class="restaurant">
	    <div class="restaurant-info">
	      <h2 class="account-heading">{{res_list.name}}</h2>
	      <p class="text-secondary"> Price:{{res_list.Price_Range}}</p>
	      <p class="text-secondary"> Cuisine Type:{{res_list.Cuisine_Type}}
	      </p>
	      <p class="text-secondary"> Phone:{{res_list.Phone}}</p>
	      <p class="text-secondary"> Address:{{res_list.Address}}</p>
	      <p class="text-secondary"> Hours:{{res_list.Hours_Start}} - {{res_list.Hours_End}}</p>
	    </div>
	  </div>
	  
	</div>
    <h3 class="account-heading">Menu</h3>

	{% for r in menu %}
	    <p class="text-secondary"> Dish Category:{{r.dish_type}}   Name:{{r.name}}    Price:${{r.price}}</p>
    {% endfor %}
</body>  
</html>

Epicure-master/rating/templates/rating/edit.html
<!DOCTYPE html>  
<html lang="en">   
<body>  
<form method="POST" class="post-form" action="{% url 'update' restaurant.res_ID %}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Update Details</h3>  
    </div>  
  </div>  
 
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Restaurant Name:</label>  
    <div class="col-sm-4">  
        <input type="text" name="name" id="id_ename" required maxlength="100" value="{{ restaurant.name }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Restaurant Phone:</label>  
    <div class="col-sm-4">  
        <input type="text" name="Phone" id="id_ephone" required maxlength="20" value="{{ restaurant.Phone }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Restaurant Address:</label>  
    <div class="col-sm-4">  
        <input type="text" name="Address" id="id_econtact" required maxlength="254" value="{{ restaurant.Address }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Update</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

Epicure-master/rating/templates/rating/index.html
<!DOCTYPE html>  
<html lang="en">   
<body> 

<h2>Search</h2>
<form action="{% url 'search'%}" method="POST">
{% csrf_token %}
<label>Name: </label><br>
<input type="text" name="name"><br>
<label>Cuision type: </label><br>
<input type="text" name="cuision_type"><br>
<label>Address: </label><br>
<input type="text" name="address"><br>
<input type="submit" value="submit">
</form>  


<h3>Search By Dish Type</h3>
<form action="{% url 'recommend'%}" method="POST">
{% csrf_token %}
<label>Dish Type: </label><br>
<input type="text" name="dish_type"><br>
<input type="submit" value="submit">
</form>  

<h3>Search By Price</h3>
<form action="{% url 'price_re'%}" method="POST">
{% csrf_token %}
<label>Dish Price: </label><br>
<input type="text" name="price"><br>
<input type="submit" value="submit">
</form> 

{% if res_list %}
    <ul>
    {% for restaurant in res_list %}

        <td>  
            <li><a href="{% url 'detail' restaurant.res_ID %}">{{ restaurant.name }}</a></li> 
            <a href="{% url 'edit' restaurant.res_ID %}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="{% url 'delete' restaurant.res_ID %}">Delete</a>  
        </td> 
    {% endfor %}
    </ul>
    <center><a href="{% url 'insert' %}" class="btn btn-primary">Add New Record</a></center> 

{% else %}
    <p>No restaurant are available.</p>
{% endif %}

</body>  
</html>

Epicure-master/rating/templates/rating/insert.html
<!DOCTYPE html>  
<html lang="en">   
<body> 
    
<form method="POST" class="post-form" action="{% url 'res' %}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Enter Details</h3>  
    </div>  
  </div> 


   <div class="form-group row">  
     <label for="name">Restaurant Name:</label>
     <input type="text" id="id_name" name="name">
    </div> 

    <div class="form-group row">  
     <label for="name">Phone:</label>
     <input type="text" id="id_Phone" name="Phone">
    </div> 


    <div class="form-group row">  
     <label for="name">Address:</label>
     <input type="text" id="id_Address" name="Address">
    </div> 

    <div class="form-group row">  
     <label for="name">Restaurant ID:</label>
     <input type="number" id="id_ID" name="res_ID">
    </div> 

 
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
</form> 
</body>  
</html>

Epicure-master/rating/templates/rating/result.html
{% if res_list %}
    <ul>
    {% for r in res_list %}
        <p class="text-secondary"> Dish Category:{{r}}</p>

    {% endfor %}
    </ul>

{% else %}
    <p>No restaurant are available.</p>
{% endif %}